# Load required libraries
import openpyxl
import pandas as pd
from Bio import Entrez
from collections import Counter
import re
import time

def rate_limit_entrez():
    """Add delay to respect NCBI's 3 requests per second limit"""
    time.sleep(0.34)  # 0.34 seconds = roughly 3 requests per second

# Load dataframes
faculty_df = pd.read_excel('BioSci_Faculty.xlsx', sheet_name='minus_teaching')
research_keywords_df = pd.read_excel('Research_Keywords.xlsx')
faculty_proposal_mesh_terms_df = pd.read_excel('Faculty_Proposal_Abstracts.xlsx', sheet_name='proposal_abstracts_sheet')
mapped_mesh_terms_df = pd.read_excel('research_keywords_cleaned_mesh_terms.xlsx', usecols=['Faculty_Full_Name', 'Mapped_Mesh_Terms'])

# Collect MeSH terms from publications
## Fetch PMIDs for each faculty member
Entrez.email = "sarkisj@uci.edu"
pmid_list = []

for index, row in faculty_df.iterrows():
    rate_limit_entrez()  # Add delay before each request
    search_term = row["Faculty_Author_Affiliation"]
    try:
        handle_search = Entrez.esearch(db="pubmed", mindate="2022", maxdate="2025", term=search_term)
        record = Entrez.read(handle_search)
        pmid_list.append(record["IdList"])
        handle_search.close()
        print(f"Fetched PMIDs for faculty {index + 1}/{len(faculty_df)}")  # Progress tracking
    except Exception as e:
        print(f"Error fetching PMIDs for {search_term}: {e}")
        pmid_list.append([])  # Add empty list if error occurs

faculty_df["pmids"] = pmid_list

## Fetch MeSH terms for each PMID
Entrez.email = "sarkisj@uci.edu"
all_pub_mesh_terms = []

for index, row in faculty_df.iterrows():
    pmid_list = row['pmids'] 
    mesh_term_texts = []
    
    if not pmid_list:  # Skip if no PMIDs
        all_pub_mesh_terms.append('')
        continue
    
    # Process PMIDs in batches of 100 instead of one by one
    batch_size = 100
    for i in range(0, len(pmid_list), batch_size):
        rate_limit_entrez()  # Add delay before each batch
        batch_pmids = pmid_list[i:i + batch_size]
        pmid_string = ','.join(batch_pmids)  # Combine PMIDs for batch request
        
        try:
            handle_mesh = Entrez.efetch(db="pubmed", id=pmid_string, rettype="xml")
            records = Entrez.read(handle_mesh)
            handle_mesh.close()
            
            # Process all records in the batch
            for record in records["PubmedArticle"]:
                medline = record["MedlineCitation"]
                mesh_headings = medline.get("MeshHeadingList", [])
                for mesh_heading in mesh_headings:
                    descriptor_name_element = mesh_heading.get("DescriptorName")
                    if descriptor_name_element:
                        descriptor_name = str(descriptor_name_element)
                        mesh_term_texts.append(descriptor_name)
        except Exception as e:
            print(f"Error fetching MeSH terms for batch: {e}")
            continue
    
    all_pub_mesh_terms.append('; '.join(mesh_term_texts))
    print(f"Processed MeSH terms for faculty {index + 1}/{len(faculty_df)}")  # Progress tracking

faculty_df['pub_mesh_terms'] = all_pub_mesh_terms

# Save checkpoint so you don't have to run API calls again
faculty_df.to_csv('pubmed_mesh_terms_checkpoint.csv', index=False)
print("Checkpoint saved: PubMed data fetched successfully!")

# Collect MeSH terms from proposal abstracts
faculty_proposal_mesh_terms_df['Proposal_Mesh_Terms'] = faculty_proposal_mesh_terms_df['Proposal_Mesh_Terms'].astype(str)
proposal_mesh_terms_df = faculty_proposal_mesh_terms_df.groupby('Faculty_Full_Name')['Proposal_Mesh_Terms'].agg(lambda x: '; '.join(x)).reset_index()

# Merge dataframes
merged_df = pd.merge(faculty_df, proposal_mesh_terms_df, on='Faculty_Full_Name', how='left')
merged_df.drop(columns=['Faculty_Author_Affiliation'], inplace=True)
combined_faculty_df = pd.merge(merged_df, mapped_mesh_terms_df, on="Faculty_Full_Name", how='left')

# Fill NaN values with empty strings
combined_faculty_df['Proposal_Mesh_Terms'] = combined_faculty_df['Proposal_Mesh_Terms'].fillna('')
combined_faculty_df['Mapped_Mesh_Terms'] = combined_faculty_df['Mapped_Mesh_Terms'].fillna('')
combined_faculty_df['pub_mesh_terms'] = combined_faculty_df['pub_mesh_terms'].fillna('')

# Remove unhelpful MeSH terms from all columns before weighting
remove_terms_set = set([
    "Animals", "Biology", "Humans", "Rats", "Mice", "Male", "Female",
    "Disease Models, Animal", "Mice, Transgenic", "Mice, Inbred C57BL",
    "Mice, Knockout", "Adult", "Middle Aged", "Models, Theoretical",
    "Models, Biological", "Models, Animal", "Mentors", "Mentoring",
    "Universities", "Drosophila", "Mammals", "Faculty", "Research Design",
    "Follow-Up Studies", "United States", "Goals", "Preliminary Data", "Students", "Feedback",
    "2',5'-oligoadenylate",
    "3T3-L1 Cells",
    "5' Untranslated Regions",
    "5'-Nucleotidase",
    "5-Methylcytosine",
    "6-methyladenine",
    "ADP-ribosyl Cyclase",
    "Absorptiometry, Photon",
    "Academia",
    "Academic Performance",
    "Academies and Institutes",
    "Access to Information",
    "Acer",
    "Acetyl Coenzyme A",
    "Acetylation",
    "Acetylcholine",
    "Actin Cytoskeleton",
    "Actins",
    "Acute Disease",
    "Acyclovir",
    "Acyltransferases",
    "Adaptive Clinical Trials as Topic",
    "Additional Terms",
    "Adenosine",
    "Adenosine Diphosphate",
    "Adenosine Triphosphate",
    "Administration, Inhalation",
    "Administration, Intranasal",
    "Administration, Intravenous",
    "Administration, Oral",
    "Adolescent",
    "Africa",
    "Agave",
    "Age Factors",
    "Aged",
    "Aged, 80 and over",
    "Aging",
    "Agriculture",
    "Air",
    "Air Pollutants",
    "Air Pollution",
    "Aircraft",
    "Alabama",
    "Alanine Dehydrogenase",
    "Alaska",
    "Aldehyde Oxidoreductases",
    "Algorithms",
    "Alkaline Phosphatase",
    "Alkylating Agents",
    "Alleles",
    "Allosteric Site",
    "Alternaria",
    "Alternative Splicing",
    "Altitude",
    "Ambulatory Care Facilities",
    "Ambystoma mexicanum",
    "American Indian or Alaska Native",
    "Amiloride",
    "Amines",
    "Amino Acid Sequence",
    "Amino Acid Substitution",
    "Amino Acids",
    "Amino Sugars",
    "Aminopeptidases",
    "Aminopyridines",
    "Ammonium Compounds",
    "Ampicillin",
    "Amputation, Surgical",
    "Amylases",
    "Amyloid",
    "Anaphase-Promoting Complex-Cyclosome",
    "Androgens",
    "Anemia",
    "Anesthetics",
    "Aneuploidy",
    "Aniline Compounds",
    "Animal Care Committees",
    "Animal Communication",
    "Animal Husbandry",
    "Animals, Domestic",
    "Animals, Genetically Modified",
    "Animals, Laboratory",
    "Animals, Wild",
    "Anisotropy",
    "Anniversaries and Special Events",
    "Anti-Infective Agents, Local",
    "Antibodies",
    "Antibodies, Blocking",
    "Antibodies, Monoclonal",
    "Antibodies, Monoclonal, Humanized",
    "Antibodies, Neutralizing",
    "Antibodies, Viral",
    "Antigen-Antibody Reactions",
    "Antigens",
    "Antigens, CD",
    "Antigens, CD1",
    "Antioxidants",
    "Apoptosis",
    "Appendectomy",
    "Aquaporins",
    "Archaea",
    "Archaeology",
    "Arginine",
    "Arm",
    "Artificial Intelligence",
    "Ascitic Fluid",
    "Asia, Eastern",
    "Asian",
    "Asian American Native Hawaiian and Pacific Islander",
    "Asparagine",
    "Assessment of Medication Adherence",
    "Asymptomatic Infections",
    "Atlases as Topic",
    "Atmosphere",
    "Atrophy",
    "Australia",
    "Authorship",
    "Autopsy",
    "Avatar",
    "Awards and Prizes",
    "Bacteria",
    "Bacterial Physiological Phenomena",
    "Bacterial Proteins",
    "Bacteriophage P22",
    "Bacteriophage T7",
    "Base Pairing",
    "Base Sequence",
    "Basement Membrane",
    "Bayes Theorem",
    "Bays",
    "Behavior",
    "Benchmarking",
    "Benzamides",
    "Benzothiazoles",
    "Betalains",
    "Bevacizumab",
    "Bias",
    "Bicarbonates",
    "Bicyclic Monoterpenes",
    "Big Data",
    "Biliverdine",
    "Binding Sites",
    "Biochemistry",
    "Biolistics",
    "Biological Phenomena",
    "Biological Products",
    "Biological Science Disciplines",
    "Biological Specimen Banks",
    "Biological Transport",
    "Biological Variation, Population",
    "Biomass",
    "Biomedical Research",
    "Biophysics",
    "Bioreactors",
    "Biosynthetic Pathways",
    "Biota",
    "Biotin",
    "Bipolar Disorder",
    "Black or African American",
    "Blister",
    "Blood Component Removal",
    "Blotting, Western",
    "Body Fluids",
    "Brazil",
    "Breast",
    "Breeding",
    "Bronchoalveolar Lavage Fluid",
    "Budgets",
    "C9orf72 Protein",
    "CCCTC-Binding Factor",
    "CD4 Antigens",
    "CDC2 Protein Kinase",
    "CHO Cells",
    "CRISPR-Associated Proteins",
    "CRISPR-Cas Systems",
    "Cadaver",
    "Cadmium",
    "Calcinosis",
    "Calcium",
    "California",
    "Canada",
    "Capacity Building",
    "Capsid",
    "Carbohydrates",
    "Carbon",
    "Carbon Dioxide",
    "Carbon Monoxide",
    "Carboplatin",
    "Carboxylesterase",
    "Caregivers",
    "Carnivory",
    "Carrier Proteins",
    "Cartilage",
    "Case-Control Studies",
    "Casein Kinase 1 epsilon",
    "Caspase 1",
    "Caspase 3",
    "Caspase 8",
    "Catalysis",
    "Catalytic Domain",
    "Cataract",
    "Causality",
    "Cause of Death",
    "Cdc20 Proteins",
    "Cell Adhesion",
    "Cell Biology",
    "Cell Body",
    "Cell Competition",
    "Cell Culture Techniques",
    "Cell Cycle",
    "Cell Death",
    "Cell Fractionation",
    "Cell Line",
    "Cell Line, Transformed",
    "Cell Line, Tumor",
    "Cell Membrane",
    "Cell Nucleus",
    "Cell Proliferation",
    "Cell Separation",
    "Cell Shape",
    "Cell Surface Extensions",
    "Cell Survival",
    "Cell Tracking",
    "Cells, Cultured",
    "Cellulase",
    "Cellulases",
    "Censuses",
    "Centenarians",
    "Centers for Disease Control and Prevention, U.S.",
    "Central Nervous System",
    "Centrosome",
    "Ceramides",
    "Characidae",
    "Checklist",
    "Chemistry, Bioinorganic",
    "Chemistry, Pharmaceutical",
    "Child, Preschool",
    "Chimera",
    "Chin",
    "China",
    "Chromatin",
    "Chromatin Immunoprecipitation",
    "Chromatin Immunoprecipitation Sequencing",
    "Chromatography, Gas",
    "Chromatography, High Pressure Liquid",
    "Chromatography, Liquid",
    "Chromosomal Proteins, Non-Histone",
    "Chromosome Mapping",
    "Chromosomes",
    "Chromosomes, Human, Pair 17",
    "Chromosomes, Human, Pair 21",
    "Chromosomes, Human, Pair 8",
    "Chromosomes, Plant",
    "Chronic Disease",
    "Cidofovir",
    "Cisplatin",
    "Cities",
    "Citizen Science",
    "Class III Phosphatidylinositol 3-Kinases",
    "Clemastine",
    "Clergy",
    "Climate",
    "Clinical Protocols",
    "Clinical Relevance",
    "Clinical Trials Data Monitoring Committees",
    "Clone Cells",
    "Clozapine",
    "Cluster Analysis",
    "Clustered Regularly Interspaced Short Palindromic Repeats",
    "Clustered Regularly Interspaced Short Paradromic Repeats",
    "Clusterin",
    "Cobalt",
    "Coculture Techniques",
    "Codon, Nonsense",
    "Codon, Terminator",
    "Cognitive Reserve",
    "Cohort Studies",
    "Coinfection",
    "Colchicine",
    "Cold Temperature",
    "Collagen",
    "Colombia",
    "Color",
    "Colorado",
    "Coloring Agents",
    "Communicable Disease Control",
    "Communication",
    "Communication Barriers",
    "Community-Institutional Relations",
    "Comorbidity",
    "Comprehension",
    "Computers",
    "Conditioning, Operant",
    "Confidence Intervals",
    "Congo Red",
    "Connectome",
    "Consensus",
    "Conserved Sequence",
    "Consummatory Behavior",
    "Control Groups",
    "Cost of Illness",
    "Cost-Benefit Analysis",
    "Costa Rica",
    "CpG Islands",
    "Cranial Irradiation",
    "Craving",
    "Critical Illness",
    "Critical Pathways",
    "Cross Infection",
    "Cross-Linking Reagents",
    "Cross-Sectional Studies",
    "Cryopreservation",
    "Crystallization",
    "Crystallography",
    "Cues",
    "Cultural Diversity",
    "Culture Media",
    "Culture Media, Conditioned",
    "Cuprizone",
    "Curriculum",
    "Cyclic AMP",
    "Cyclic GMP",
    "Cyclic N-Oxides",
    "Cyclin B",
    "Cyclin B1",
    "Cyclin B2",
    "Cyclin-Dependent Kinase 9",
    "Cyclin-Dependent Kinase Inhibitor Proteins",
    "Cyclin-Dependent Kinases",
    "Cyclization",
    "Cyclophosphamide",
    "Cysteine",
    "Cytokinesis",
    "Cytomegalovirus",
    "Cytoplasm",
    "Cytoskeleton",
    "Cytosol",
    "Cytotoxins",
    "DNA",
    "DNA Adducts",
    "DNA Contamination",
    "DNA Copy Number Variations",
    "DNA Glycosylases",
    "DNA Replication",
    "DNA, Ancient",
    "DNA, Satellite",
    "DNA, Viral",
    "DNA-Directed DNA Polymerase",
    "DNA-Directed RNA Polymerases",
    "Dancing",
    "Dasatinib",
    "Data Aggregation",
    "Data Analysis",
    "Data Collection",
    "Data Management",
    "Data Science",
    "Databases, Factual",
    "Daunorubicin",
    "Decitabine",
    "Deep Learning",
    "Default Mode Network",
    "Dehydration",
    "Delayed Diagnosis",
    "Delivery of Health Care",
    "Demography",
    "Dendrimers",
    "Deoxycytidine",
    "Dermabrasion",
    "Desiccation",
    "Desmoglein 1",
    "Desmoglein 3",
    "Developed Countries",
    "Diagnosis",
    "Diagnosis, Differential",
    "Diagnostic Errors",
    "Diet",
    "Dietary Supplements",
    "Diffusion",
    "Diffusion Magnetic Resonance Imaging",
    "Diffusion Tensor Imaging",
    "Dihydroxyphenylalanine",
    "Dimerization",
    "Dioxygenases",
    "Diploidy",
    "Disclosure",
    "Disease",
    "Disease-Free Survival",
    "Dissolved Organic Matter",
    "Disulfides",
    "Documentation",
    "Domestication",
    "Dose-Response Relationship, Drug",
    "Double-Blind Method",
    "Down-Regulation",
    "Doxorubicin",
    "Doxycycline",
    "Drinking Water",
    "Dronabinol",
    "Drosophila Proteins",
    "Drug Carriers",
    "Drug Evaluation",
    "Drug Labeling",
    "Drug Liberation",
    "Drug Repositioning",
    "Dynactin Complex",
    "Dystonia",
    "Dystonia 3, Torsion, X-Linked",
    "ET protocol",
    "Early Diagnosis",
    "Earth, Planet",
    "East Asian People",
    "Eating",
    "Ecology",
    "Ecotype",
    "Ectopic Gene Expression",
    "Ecuador",
    "Education, Graduate",
    "Educational Measurement",
    "Educational Status",
    "Elastomers",
    "Electron Transport",
    "Electronic Mail",
    "Electronic Nicotine Delivery Systems",
    "Electrons",
    "Embryonic Stem Cells",
    "Embryophyta",
    "Emotions",
    "Employment",
    "Endocrinology",
    "Endodeoxyribonucleases",
    "Endopeptidases",
    "Endoplasmic Reticulum",
    "Endoribonucleases",
    "Endosomes",
    "Enhancer Elements, Genetic",
    "Entropy",
    "Environment",
    "Environmental Justice",
    "Environmental Science",
    "Enzyme Inhibitors",
    "Enzymes",
    "Epidemiologic Studies",
    "Epidemiology",
    "Epigenesis, Genetic",
    "Epilepsies, Partial",
    "Epistasis, Genetic",
    "Epistaxis",
    "Epithelial Cell Adhesion Molecule",
    "Epitope Mapping",
    "Epitopes",
    "Escherichia coli",
    "Escherichia coli Proteins",
    "Esters",
    "Estonia",
    "Ethanol",
    "Ethics Committees, Research",
    "Ethylene Glycols",
    "Eukaryota",
    "Eukaryotic Cells",
    "Europe",
    "Eutheria",
    "Evidence Gaps",
    "Executive Function",
    "Exons",
    "Exoskeleton Device",
    "Extracellular Fluid",
    "Extracellular Matrix",
    "Extracellular Space",
    "Extremities",
    "Extrude",
    "Eyebrows",
    "Eyelids",
    "Face",
    "Family",
    "Farmers",
    "Farms",
    "Fasting",
    "Fatty Acids, Volatile",
    "Feasibility Studies",
    "Feces",
    "Feedback\n DNA, Single-Stranded\n Learning\n Ecology\n Empirical Research",
    "Feedback, Physiological",
    "Fellowships and Scholarships",
    "Fermentation",
    "Fetal Stem Cells",
    "Fetus",
    "Ficus",
    "Financial Management",
    "Financial Support",
    "Financing, Organized",
    "Fingolimod Hydrochloride",
    "Flagella",
    "Florida",
    "Flow Cytometry",
    "Fluorescence",
    "Fluorescent Antibody Technique",
    "Fluorocarbons",
    "Fluorouracil",
    "Flutamide",
    "Fluticasone",
    "Formate Dehydrogenases",
    "Fossils",
    "Frailty",
    "Freezing",
    "Fresh Water",
    "Fructose",
    "Fruit",
    "Fucose",
    "Fusion Proteins, bcr-abl",
    "GTP Phosphohydrolases",
    "Gain of Function Mutation",
    "Galactosidases",
    "Galium",
    "Gametogenesis",
    "Gardening",
    "Gas Chromatography-Mass Spectrometry",
    "Gases",
    "Gelatin",
    "Gemcitabine",
    "Gene Dosage",
    "Gene Expression",
    "Gene Expression Profiling",
    "Gene Expression Regulation, Bacterial",
    "Gene Expression Regulation, Developmental",
    "Gene Expression Regulation, Enzymologic",
    "Gene Expression Regulation, Neoplastic",
    "Gene Expression Regulation, Plant",
    "Gene Expression Regulation, Viral",
    "Gene Knock-In Techniques",
    "Gene Knockdown Techniques",
    "Gene Knockout Techniques",
    "Gene Ontology",
    "Gene Rearrangement",
    "Gene Regulatory Networks",
    "Gene Transfer, Horizontal",
    "Generative Artificial Intelligence",
    "Genes",
    "Genes, Bacterial",
    "Genes, Duplicate",
    "Genes, Essential",
    "Genes, Plant",
    "Genes, Reporter",
    "Genes, Suppressor",
    "Genetic Background",
    "Genetic Code",
    "Genetic Drift",
    "Genetic Engineering",
    "Genetic Fitness",
    "Genetic Introgression",
    "Genetic Load",
    "Genetic Phenomena",
    "Genetic Techniques",
    "Genetic Testing",
    "Genetic Variation",
    "Genetics",
    "Genome",
    "Genome Size",
    "Genomics",
    "Genotype",
    "Geography",
    "Germ-Free Life",
    "Global Health",
    "Glucocorticoids",
    "Glucose",
    "Glucose 1-Dehydrogenase",
    "Glucose Transporter Type 1",
    "Glutamic Acid",
    "Glutamine",
    "Glutathione",
    "Glycated Hemoglobin",
    "Glycolysis",
    "Glycoside Hydrolases",
    "Gold",
    "Government",
    "Government Agencies",
    "Gram-Negative Bacteria",
    "Green Fluorescent Proteins",
    "Group Dynamics",
    "Guanosine Triphosphate",
    "Guidelines as Topic",
    "Guyana",
    "H3B-8800",
    "HCT116 Cells",
    "HEK293 Cells",
    "HLA Antigens",
    "HMGB2 Protein",
    "Hand Strength",
    "Haploidy",
    "Haploinsufficiency",
    "Haplotypes",
    "Hawaii",
    "HeLa Cells",
    "Head",
    "Health",
    "Health Services Accessibility",
    "Health Surveys",
    "Healthy Volunteers",
    "Heart",
    "Heart Rate",
    "Heating",
    "Helium",
    "Heme Oxygenase (Decyclizing)",
    "Hemeproteins",
    "Hepatocyte Growth Factor",
    "Herbivory",
    "Heredity",
    "Heterochromatin",
    "Heterocyclic Compounds, 3-Ring",
    "Heterografts",
    "Heterozygote",
    "HhAntag691",
    "High-Throughput Nucleotide Sequencing",
    "High-Throughput Screening Assays",
    "Hispanic or Latino",
    "Histology",
    "Histone Code",
    "Histone Deacetylase 1",
    "Histone Deacetylase 2",
    "Histone Demethylases",
    "Histone Methyltransferases",
    "Histones",
    "History, 20th Century",
    "History, 21st Century",
    "History, Ancient",
    "Home Environment",
    "Homozygote",
    "Honduras",
    "Hormones",
    "Hospital Mortality",
    "Hospitalization",
    "Host Specificity",
    "Hot Temperature",
    "Household Work",
    "Housing",
    "Housing Quality",
    "Human Activities",
    "Human Body",
    "Human Genetics",
    "Humanities",
    "Humans",
    "Humidity",
    "Hunting",
    "Hybridization, Genetic",
    "Hydrogen",
    "Hydrogen Peroxide",
    "Hydrogen-Ion Concentration",
    "Hydrogenase",
    "Hydrology",
    "Hydrolysis",
    "Hydroxyl Radical",
    "Hydroxymethylglutaryl-CoA Reductase Inhibitors",
    "Hyperglycemia",
    "Hypertrophy",
    "INDEL Mutation",
    "Image Cytometry",
    "Immune System",
    "Immunity",
    "Immunization, Passive",
    "Immunocompromised Host",
    "Immunogenic Cell Death",
    "Immunoglobulin G",
    "Immunoglobulin G4-Related Disease",
    "Immunoglobulins",
    "Immunohistochemistry",
    "Immunologic Factors",
    "Immunologic Techniques",
    "Immunophenotyping",
    "In Situ Hybridization",
    "In Situ Hybridization, Fluorescence",
    "Incidence",
    "Incubators",
    "Indian Ocean",
    "Indicators and Reagents",
    "Individuality",
    "Indolizines",
    "Indonesia",
    "Induced Pluripotent Stem Cells",
    "Industrial Development",
    "Infant",
    "Information Dissemination",
    "Information Services",
    "Information Sources",
    "Informed Consent",
    "Injections, Intraperitoneal",
    "Inosine",
    "Inpatients",
    "Insect Proteins",
    "Insecta",
    "Insulins",
    "Insulysin",
    "Insurance Coverage",
    "Integrases",
    "Integrin alpha6",
    "Integrins",
    "Intercellular Adhesion Molecule-1",
    "Interdisciplinary Communication",
    "Interdisciplinary Research",
    "Interferon-gamma",
    "Interleukin-1",
    "Interleukin-17",
    "Interleukin-18",
    "Interleukin-1beta",
    "Interleukin-2",
    "Intermediate Filaments",
    "International Cooperation",
    "Internship and Residency",
    "Interpersonal Relations",
    "Intravital Microscopy",
    "Intrinsically Disordered Proteins",
    "Introns",
    "Iron",
    "Isocitrate Dehydrogenase",
    "Isomerism",
    "Isometric Contraction",
    "Isothiocyanates",
    "Isotopes",
    "Judgment",
    "Kansas",
    "Karyotype",
    "Keloid",
    "Ketoglutaric Acids",
    "Ketones",
    "Kinesins",
    "Kinetics",
    "Kinetochores",
    "Laboratories",
    "Lactic Acid",
    "Lamin Type A",
    "Language",
    "Large Language Models",
    "Larva",
    "Latent Infection",
    "Latin America",
    "Leadership",
    "Learning",
    "Leg",
    "Length of Stay",
    "Leucine",
    "Leucovorin",
    "Lidocaine",
    "Life Change Events",
    "Life Cycle Stages",
    "Life History Traits",
    "Life Style",
    "Ligands",
    "Ligases",
    "Light",
    "Likelihood Functions",
    "Linezolid",
    "Lipase",
    "Lipid A",
    "Lipid Droplets",
    "Lipid Peroxidation",
    "Lipids",
    "Lipopolysaccharides",
    "Liquid Biopsy",
    "Liquid Chromatography-Mass Spectrometry",
    "Liquidambar",
    "Literacy",
    "Live Birth",
    "Logic",
    "Logistic Models",
    "Loma",
    "Longitudinal Studies",
    "Los Angeles",
    "Losartan",
    "Loss of Function Mutation",
    "Love",
    "Lower Extremity",
    "Lubricants",
    "Lymph Nodes",
    "Lymphocytes",
    "Lymphoid Tissue",
    "Lynx",
    "Lysine",
    "M Phase Cell Cycle Checkpoints",
    "MAP Kinase Signaling System",
    "Machine Learning",
    "Macrocystis",
    "Macromolecular Substances",
    "Macronucleus",
    "Magnetic Fields",
    "Magnetic Phenomena",
    "Magnetic Resonance Imaging",
    "Magnetic Resonance Spectroscopy",
    "Magnets",
    "Magnolia",
    "Malathion",
    "Malawi",
    "Marketing",
    "Masks",
    "Mass Behavior",
    "Mass Spectrometry",
    "Maternal Health",
    "Mating Preference, Animal",
    "Matrix Metalloproteinase 9",
    "Medicaid",
    "Medical History Taking",
    "Medical Oncology",
    "Medication Adherence",
    "Medicine",
    "Meiosis",
    "Membrane Glycoproteins",
    "Membrane Proteins",
    "Membranes",
    "Memory",
    "Mental Fatigue",
    "Menthol",
    "Metadata",
    "Metagenome",
    "Metagenomics",
    "Metal Nanoparticles",
    "Metals",
    "Metals, Heavy",
    "Metaplasia",
    "Metformin",
    "Methane",
    "Methanol",
    "Methylation",
    "Metronidazole",
    "Mevalonic Acid",
    "Mexican Americans",
    "Mexico",
    "Mice",
    "Mice, Inbred BALB C",
    "Mice, Inbred NOD",
    "Mice, Nude",
    "Mice, Obese",
    "MicroRNAs",
    "Microalgae",
    "Microbiology",
    "Microelectrodes",
    "Micronucleus, Germline",
    "Microscopy",
    "Microscopy, Confocal",
    "Microscopy, Electron",
    "Microscopy, Electron, Scanning Transmission",
    "Microscopy, Electron, Transmission",
    "Microscopy, Fluorescence",
    "Microsomes",
    "Microtubule-Associated Proteins",
    "Microtubules",
    "Military Personnel",
    "Minority Groups",
    "Mitochondria",
    "Mitogen-Activated Protein Kinase 1",
    "Mitosis",
    "Mobile Applications",
    "Models, Chemical",
    "Models, Genetic",
    "Models, Molecular",
    "Models, Neurological",
    "Molecular Biology",
    "Molecular Conformation",
    "Molecular Motor Proteins",
    "Molecular Sequence Annotation",
    "Molecular Structure",
    "Molybdoferredoxin",
    "Monomeric GTP-Binding Proteins",
    "Monoterpenes",
    "Montana",
    "Morbidity",
    "Morocco",
    "Morphine",
    "Morpholines",
    "Mortality",
    "Motion",
    "Movement",
    "Mpox (monkeypox)",
    "Multifactorial Inheritance",
    "Multigene Family",
    "Multiomics",
    "Multiple Organ Failure",
    "Multivariate Analysis",
    "Muscle Spindles",
    "Muscles",
    "Museums",
    "Mutagenesis",
    "Mutagenesis, Insertional",
    "Mutation",
    "Mutation, Missense",
    "Myeloid Differentiation Factor 88",
    "Myoglobin",
    "Mytilus",
    "N-Methylaspartate",
    "N-Myc Proto-Oncogene Protein",
    "N-nitrosoiminodiacetic acid",
    "NAD",
    "NADP",
    "NAV1.8 Voltage-Gated Sodium Channel",
    "NF-E2-Related Factor 2",
    "NF-KappaB Inhibitor alpha",
    "NLR Family, Pyrin Domain-Containing 3 Protein",
    "Nanoparticles",
    "Nanostructures",
    "National Center for Advancing Translational Sciences (U.S.)",
    "National Eye Institute (U.S.)",
    "National Institute of Allergy and Infectious Diseases (U.S.)",
    "National Institute of General Medical Sciences (U.S.)",
    "Native Hawaiian or Pacific Islander",
    "Natural History",
    "Natural Killer T-Cells",
    "Natural Science Disciplines",
    "Needs Assessment",
    "Negotiating",
    "Neoadjuvant Therapy",
    "Neon",
    "Neprilysin",
    "Nerve Growth Factor",
    "Nerve Net",
    "Nervous System",
    "Neural Networks, Computer",
    "Neuregulin-1",
    "Neurites",
    "Neuroanatomy",
    "Neurobiology",
    "Neurons, Efferent",
    "Neurosciences",
    "Nevus",
    "New Mexico",
    "New York",
    "Niacinamide",
    "Nicotiana",
    "Nicotinamide Mononucleotide",
    "Nicotinamide-Nucleotide Adenylyltransferase",
    "Nitrates",
    "Nitric Oxide",
    "Nitrification",
    "Nitrogen",
    "Nivolumab",
    "Nonlinear Dynamics",
    "Normal Distribution",
    "North America",
    "Nuclear Lamina",
    "Nuclear Matrix-Associated Proteins",
    "Nuclear Proteins",
    "Nucleic Acid Amplification Techniques",
    "Nucleic Acid Conformation",
    "Nucleic Acids",
    "Nucleosides",
    "Nucleosomes",
    "Nucleotide Motifs",
    "Nucleotides",
    "Nucleotides, Cyclic",
    "Nucleotidyltransferases",
    "Nutrients",
    "Occupations",
    "Ohio",
    "Oligodeoxyribonucleotides",
    "Oligonucleotides",
    "Oligonucleotides, Antisense",
    "Oncology Nursing",
    "One Health",
    "Open Reading Frames",
    "Ophthalmic Solutions",
    "Opsins",
    "Optical Imaging",
    "Optimism",
    "Orbital Implants",
    "Oregon",
    "Organelles",
    "Organic Chemicals",
    "Organizations",
    "Outcome Assessment, Health Care",
    "Outsourced Services",
    "Ovarian Reserve",
    "Oviposition",
    "Ovosiston",
    "Oxaliplatin",
    "Oxazoles",
    "Oxidation-Reduction",
    "Oxidative Phosphorylation",
    "Oxides",
    "Oxidoreductases",
    "Oxygen",
    "Oxytocin",
    "PTEN Phosphohydrolase",
    "Paclitaxel",
    "Pandemic Preparedness",
    "Parents",
    "Paromomycin",
    "Particulate Matter",
    "Patch-Clamp Techniques",
    "Patient Care",
    "Patient Discharge",
    "Patient Preference",
    "Pazopanib",
    "Pediatrics",
    "Pedigree",
    "Peer Review",
    "Penetrance",
    "Peptide Fragments",
    "Peptide Hydrolases",
    "Peptides",
    "Perfusion",
    "Periodicals as Topic",
    "Periodicity",
    "Permeability",
    "Personnel Selection",
    "Pharmaceutical Preparations",
    "Pharmacology",
    "Phase Separation",
    "Phenomics",
    "Phenotype",
    "Phenylephrine",
    "Philippines",
    "Phosphates",
    "Phosphatidylinositol-3,4,5-Trisphosphate 5-Phosphatases",
    "Phosphatidylinositols",
    "Phosphoglycerate Dehydrogenase",
    "Phosphoproteins",
    "Phosphoric Monoester Hydrolases",
    "Phosphorus",
    "Phosphorylation",
    "Phosphotransferases",
    "Phosphotransferases (Alcohol Group Acceptor)",
    "Phototaxis",
    "Phylogeny",
    "Physicians",
    "Physics",
    "Physiological Phenomena",
    "Physiology",
    "Pilot Projects",
    "Pinus",
    "Pioglitazone",
    "Piwi-Interacting RNA",
    "Planets",
    "Planning Techniques",
    "Plant Leaves",
    "Plant Physiological Phenomena",
    "Plants",
    "Plasmids",
    "Platinum",
    "Point Mutation",
    "Policy",
    "Policy Making",
    "Poly Adenosine Diphosphate Ribose",
    "Polyadenylation",
    "Polyamines",
    "Polyethylene Terephthalates",
    "Polymerase Chain Reaction",
    "Polymers",
    "Polymorphism, Single Nucleotide",
    "Polymyxin B",
    "Polypharmacology",
    "Polysomnography",
    "Polysorbates",
    "Polyunsaturated Alkamides",
    "Portugal",
    "Positron Emission Tomography Computed Tomography",
    "Positron-Emission Tomography",
    "Postdoctoral Training",
    "Postmortem Changes",
    "Postsynaptic Potential Summation",
    "Preceptorship",
    "Prednisolone",
    "Pregnane X Receptor",
    "Prenatal Exposure Delayed Effects",
    "Prevalence",
    "Primates",
    "Printing, Three-Dimensional",
    "Private Sector",
    "Probability",
    "Professional Competence",
    "Prognosis",
    "Program Evaluation",
    "Programming Languages",
    "Progression-Free Survival",
    "Prokaryotic Cells",
    "Proof of Concept Study",
    "Proprotein Convertase 9",
    "Prospective Studies",
    "Protein Binding",
    "Protein Biosynthesis",
    "Protein C",
    "Protein Conformation, alpha-Helical",
    "Protein Conformation, beta-Strand",
    "Protein Interaction Maps",
    "Protein Isoforms",
    "Protein Kinase C",
    "Protein Kinase Inhibitors",
    "Protein Kinases",
    "Protein Multimerization",
    "Protein Phosphatase 2",
    "Protein Precursors",
    "Protein Prenylation",
    "Protein Processing, Post-Translational",
    "Protein Serine-Threonine Kinases",
    "Protein Stability",
    "Protein Subunits",
    "Protein Transport",
    "Protein Tyrosine Phosphatase, Non-Receptor Type 11",
    "Protein-Tyrosine Kinases",
    "Proteins",
    "Proteolysis",
    "Proteome",
    "Proteostasis",
    "Proteostasis Deficiencies",
    "Protons",
    "Protoplasts",
    "Protozoan Proteins",
    "Pseudogenes",
    "Pseudopodia",
    "Pseudouridine",
    "Psychiatrists",
    "Psychiatry",
    "Public Health",
    "Publishing",
    "Pupa",
    "Putrescine",
    "Pyocyanine",
    "Pyridines",
    "Pyridinium Compounds",
    "Pyrimidines",
    "Pyrin",
    "Pyrin Domain",
    "Pyruvaldehyde",
    "Pyruvic Acid",
    "Qualitative Research",
    "Quality Control",
    "Quinolines",
    "R-Loop Structures",
    "RNA",
    "RNA 3' End Processing",
    "RNA Polymerase II",
    "RNA Precursors",
    "RNA Stability",
    "RNA, Guide, CRISPR-Cas Systems",
    "RNA, Messenger",
    "RNA, Plant",
    "RNA, Ribosomal, 16S",
    "RNA, Small Interfering",
    "RNA, Small Untranslated",
    "RNA, Untranslated",
    "RNA, Viral",
    "RNA-Seq",
    "Rabbits",
    "Racial Groups",
    "Radiology",
    "Random Allocation",
    "Rats, Long-Evans",
    "Rats, Sprague-Dawley",
    "Reactive Nitrogen Species",
    "Reading",
    "Real-Time Polymerase Chain Reaction",
    "Receptor, Anaphylatoxin C5a",
    "Receptor, Cannabinoid, CB1",
    "Receptors, Antigen, T-Cell",
    "Receptors, Immunologic",
    "Recombinant Proteins",
    "Recombination, Genetic",
    "Recommended Dietary Allowances",
    "Recreation",
    "Rectum",
    "Recurrence",
    "Reducing Agents",
    "Reference Values",
    "Referral and Consultation",
    "Regeneration",
    "Registries",
    "Regulator",
    "Remote Sensing",
    "Repetitive Sequences, Nucleic Acid",
    "Reproducibility of Results",
    "Republic of Korea",
    "Research",
    "Research Personnel",
    "Research Report",
    "Research Subjects",
    "Response Elements",
    "Retrospective Studies",
    "Reverse Genetics",
    "Ribonucleotides",
    "Ribosomal Protein S6 Kinases, 70-kDa",
    "Ribosomes",
    "Rifampin",
    "Risk Assessment",
    "Risk Factors",
    "Robotics",
    "Rodentia",
    "Rosiglitazone",
    "Rotation",
    "Running",
    "S Phase",
    "S-Adenosylmethionine",
    "SELEX Aptamer Technique",
    "SOS Response, Genetics",
    "Saliva",
    "Salts",
    "Sand",
    "Saponins",
    "Scalp",
    "Schools",
    "Second Messenger Systems",
    "Secretome",
    "Selection, Genetic",
    "Self Administration",
    "Self Report",
    "Sensation",
    "Sequence Analysis",
    "Sequence Analysis, DNA",
    "Sequence Analysis, RNA",
    "Sequence Deletion",
    "Sequence Homology",
    "Serial Passage",
    "Serine",
    "Serine Endopeptidases",
    "Sex Characteristics",
    "Signal Transduction",
    "Signal-To-Noise Ratio",
    "Silicon",
    "Silicon Dioxide",
    "Single-Cell Analysis",
    "Single-Domain Antibodies",
    "Sirolimus",
    "Skull",
    "Smartphone",
    "Smegmamorpha",
    "Social Media",
    "Social Mobility",
    "Social Planning",
    "Social Responsibility",
    "Social Sciences",
    "Societies, Nursing",
    "Societies, Scientific",
    "Sodium Chloride",
    "Software",
    "Solubility",
    "Solutions",
    "Solvents",
    "South America",
    "Spain",
    "Specialty Boards",
    "Species Specificity",
    "Specimen Handling",
    "Spectrum Analysis",
    "Spectrum Analysis, Raman",
    "Spermidine",
    "Sphingomonas",
    "Sphingosine",
    "Spinal Puncture",
    "Spindle Apparatus",
    "Spleen",
    "Sputum",
    "Squalene",
    "Staining and Labeling",
    "Standard of Care",
    "Static Electricity",
    "Statistics, Nonparametric",
    "Stem Cell Research",
    "Stem Cells",
    "Stereotaxic Techniques",
    "Streptavidin",
    "Substrate Specificity",
    "Sugars",
    "Sulfoxides",
    "Sulfur",
    "Surveys and Questionnaires",
    "Survival Rate",
    "Sweden",
    "Swimming",
    "Switzerland",
    "Synthetic Lethal Mutations",
    "Systems Theory",
    "T-Lymphocytes",
    "THP-1 Cells",
    "Tacrolimus",
    "Tamoxifen",
    "Tandem Mass Spectrometry",
    "Tandem Repeat Sequences",
    "Technology",
    "Tecovirimat",
    "Telomere",
    "Temozolomide",
    "Temperature",
    "Terminology as Topic",
    "Terpenes",
    "Testosterone",
    "Tetracycline",
    "Tetracyclines",
    "Therapeutic Index",
    "Therapeutics",
    "Thermodynamics",
    "Thiazolidinediones",
    "Thinking",
    "Thromboinflammation",
    "Thymidine Kinase",
    "Tibet",
    "Ticks",
    "Tight Junctions",
    "Time",
    "Time Factors",
    "Time-Lapse Imaging",
    "Tissue Distribution",
    "Tissue Donors",
    "Tissues",
    "Tomography, X-Ray Computed",
    "Torque",
    "Trans-Activators",
    "Transcription Factor 7-Like 1 Protein",
    "Transcription Factor MTF-1",
    "Transcription Factor RelA",
    "Transcription, Genetic",
    "Transcriptome",
    "Transcytosis",
    "Transfection",
    "Transferases",
    "Transgenes",
    "Translational Research, Biomedical",
    "Translational Science, Biomedical",
    "Translocation, Genetic",
    "Transplantation Conditioning",
    "Transplantation, Haploidentical",
    "Transplantation, Heterologous",
    "Transplantation, Homologous",
    "Treatment Outcome",
    "Tretinoin",
    "Trialkyltin Compounds",
    "Triazoles",
    "Trimethoprim",
    "Tropism",
    "Trypsin",
    "Tubulin",
    "Twins, Monozygotic",
    "Tyrosine",
    "Tyrosine Kinase Inhibitors",
    "UK Biobank",
    "Ubiquitin",
    "Ultraviolet Rays",
    "Uncertainty",
    "United Kingdom",
    "United States Food and Drug Administration",
    "Up-Regulation",
    "Uracil",
    "Urea",
    "Uridine Monophosphate",
    "Urinary Bladder Neoplasms",
    "Vaccinia",
    "Vaccinia virus",
    "Vaccinology",
    "Vacuolar Proton-Translocating ATPases",
    "Vacuoles",
    "Vacuum",
    "Vancomycin",
    "Vero Cells",
    "Vertebrates",
    "Vibrio",
    "Videoconferencing",
    "Viral Proteins",
    "Viral Replication Compartments",
    "Virion",
    "Virome",
    "Virtual Reality",
    "Virulence",
    "Virulence Factors",
    "Virus Activation",
    "Viruses",
    "Viscosity",
    "Vitamin A",
    "Vitamin B 6",
    "Vitamin B Complex",
    "Vitamins",
    "Vitis",
    "Volatile Organic Compounds",
    "Volunteers",
    "Waste Disposal, Fluid",
    "Water",
    "Water Movements",
    "Water Supply",
    "Weaning",
    "Weight Gain",
    "Weight Loss",
    "Western World",
    "White",
    "White People",
    "Whole Genome Sequencing",
    "Workflow",
    "Workforce",
    "World Health Organization",
    "Writing",
    "X-Ray Absorption Spectroscopy",
    "X-Ray Diffraction",
    "X-Ray Microtomography",
    "Xenon",
    "Xylans",
    "Xylose",
    "Zinc",
    "Zinc Finger Protein GLI1",
    "Zygote",
])

def remove_terms_optimized(terms_string):
    if pd.isna(terms_string) or terms_string == '':
        return ''
    
    terms_list = [term.strip() for term in terms_string.split(';') 
                  if term.strip() 
                  and term.strip() not in remove_terms_set
                  and term.strip().lower() != "nan"  # Add this line
                  and not pd.isna(term.strip())]     # Add this line for extra safety
    return '; '.join(terms_list)

# Clean all three columns
combined_faculty_df['pub_mesh_terms'] = combined_faculty_df['pub_mesh_terms'].apply(remove_terms_optimized)
combined_faculty_df['Mapped_Mesh_Terms'] = combined_faculty_df['Mapped_Mesh_Terms'].apply(remove_terms_optimized)
combined_faculty_df['Proposal_Mesh_Terms'] = combined_faculty_df['Proposal_Mesh_Terms'].apply(remove_terms_optimized)

# Create the weighted terms (after dataframe exists and is cleaned)
def combine_mesh_terms_with_weights(row):
    """Combine terms while tracking their sources for weighting"""
    terms_with_weights = []
    
    # Publications (weight = 1)
    if row['pub_mesh_terms'] and row['pub_mesh_terms'].strip():
        pub_terms = [term.strip() for term in row['pub_mesh_terms'].split(';') if term.strip()]
        terms_with_weights.extend([(term, 1) for term in pub_terms])
    
    # Mapped terms (weight = 2)  
    if row['Mapped_Mesh_Terms'] and row['Mapped_Mesh_Terms'].strip():
        mapped_terms = [term.strip() for term in row['Mapped_Mesh_Terms'].split(';') if term.strip()]
        terms_with_weights.extend([(term, 2) for term in mapped_terms])
    
    # Proposal terms (weight = 3)
    if row['Proposal_Mesh_Terms'] and row['Proposal_Mesh_Terms'].strip():
        proposal_terms = [term.strip() for term in row['Proposal_Mesh_Terms'].split(';') if term.strip()]
        terms_with_weights.extend([(term, 3) for term in proposal_terms])
    
    return terms_with_weights

# Apply the weighting function
combined_faculty_df['Terms_With_Weights'] = combined_faculty_df.apply(combine_mesh_terms_with_weights, axis=1)

# Create combined terms string for backward compatibility
def create_combined_terms_string(terms_with_weights):
    if not terms_with_weights:
        return ''
    terms = [term for term, weight in terms_with_weights]
    return '; '.join(terms)

combined_faculty_df['Combined_Mesh_Terms'] = combined_faculty_df['Terms_With_Weights'].apply(create_combined_terms_string)

# Calculate most common item and average frequency
def find_most_common_item_vectorized(data):
    if pd.isna(data) or data == '':
        return pd.Series([None, 0])
    
    items = data.split('; ')
    item_counts = Counter(items)
    if not item_counts:
        return pd.Series([None, 0])
    
    most_common_item, max_count = item_counts.most_common(1)[0]
    average_frequency = sum(item_counts.values()) / len(item_counts)
    return pd.Series([most_common_item, average_frequency])

combined_faculty_df[['most_common_item', 'average_frequency']] = combined_faculty_df['Combined_Mesh_Terms'].apply(find_most_common_item_vectorized)

# Calculate weighted counter for top terms
weighted_counter = Counter()

for terms_with_weights in combined_faculty_df['Terms_With_Weights']:
    for term, weight in terms_with_weights:
        if term:  # Skip empty terms
            weighted_counter[term] += weight

# Calculate total weighted count
total_weighted_items = sum(weighted_counter.values())

# Get top items
top_items = weighted_counter.most_common(100)

# Print results
for item, weighted_count in top_items:
    proportion = weighted_count / total_weighted_items
    print(f"{item}: {weighted_count} ({proportion:.2%})")

# Calculate normalized scores
def calculate_weighted_normalized_scores(terms_with_weights, top_items_list):
    """Calculate normalized scores using proper weighting"""
    if not terms_with_weights:
        return {item: 0.0 for item in top_items_list}
    
    weighted_counts = {}
    total_weighted_count = 0
    
    for term, weight in terms_with_weights:
        if term in top_items_list:
            weighted_counts[term] = weighted_counts.get(term, 0) + weight
            total_weighted_count += weight
    
    if total_weighted_count == 0:
        return {item: 0.0 for item in top_items_list}
    
    normalized_scores = {}
    for item in top_items_list:
        normalized_scores[item] = weighted_counts.get(item, 0) / total_weighted_count
    
    return normalized_scores

# Get top items list
top_items_list = [item[0] for item in top_items]

# Apply weighted scoring
combined_faculty_df['Normalized_Scores'] = combined_faculty_df['Terms_With_Weights'].apply(
    lambda x: calculate_weighted_normalized_scores(x, top_items_list)
)

# Clean up to save memory
combined_faculty_df.drop(columns=['pmids'], errors='ignore', inplace=True)

# Calculate top MeSH terms for each faculty
def calculate_top_mesh_terms(faculty_mesh_terms_dict):
    for faculty, mesh_terms in faculty_mesh_terms_dict.items():
        if mesh_terms:
            term_counts = Counter(mesh_terms)
            top_terms = term_counts.most_common(3)
            print(f"{faculty}: ", end="")
            for i, (term, count) in enumerate(top_terms):
                print(f"{term}", end="")
            print()
        else:
            print(f"No MeSH terms found for {faculty}.")

combined_faculty_df['Mesh_Terms_List'] = combined_faculty_df['Combined_Mesh_Terms'].str.split(';')
combined_faculty_df['Mesh_Terms_List'] = combined_faculty_df['Mesh_Terms_List'].apply(lambda x: [item.strip() for item in x] if isinstance(x, list) else [])

# Create a dictionary with Faculty_Full_Name as keys and Mesh_Terms_List as values
faculty_mesh_terms_dict = dict(zip(combined_faculty_df['Faculty_Full_Name'], combined_faculty_df['Mesh_Terms_List']))
calculate_top_mesh_terms(faculty_mesh_terms_dict)

# Optimized unique terms function
def get_unique_terms_optimized(combined_faculty_df):
    def process_terms(terms_string):
        if pd.isna(terms_string) or terms_string == '':
            return ''
        terms_set = {term.strip() for term in terms_string.split(';') if term.strip()}
        return '; '.join(sorted(terms_set))
    
    unique_terms_series = combined_faculty_df['Combined_Mesh_Terms'].apply(process_terms)
    return dict(zip(combined_faculty_df['Faculty_Full_Name'], unique_terms_series))

# Get unique MeSH terms
unique_mesh_terms = get_unique_terms_optimized(combined_faculty_df)

# Create and save DataFrame of unique terms
unique_terms_df = pd.DataFrame(list(unique_mesh_terms.items()), columns=['Faculty_Full_Name', 'Unique_Mesh_Terms'])
unique_terms_df.to_excel('faculty_unique_mesh_terms.xlsx', index=False)

# Convert 'Normalized_Scores' dictionary column to separate columns
normalized_scores_df = combined_faculty_df['Normalized_Scores'].apply(pd.Series)

# Align indices
normalized_scores_df.index = combined_faculty_df.index

# Concatenate normalized scores to original DataFrame
combined_faculty_df = pd.concat([combined_faculty_df, normalized_scores_df], axis=1)

# Save the updated DataFrame to Excel
combined_faculty_df.to_excel('faculty_mesh_terms.xlsx', index=False)

# Prepare PCA matrix (safer column selection)
pd.options.display.max_columns = None
pd.options.display.max_rows = None

# Drop non-numeric columns to prepare for PCA (safer approach)
columns_to_keep = ['Faculty_Full_Name'] + top_items_list
pca_matrix = combined_faculty_df[columns_to_keep]

# Save PCA matrix to Excel
pca_matrix.to_excel('faculty_mesh_terms_matrix.xlsx', index=False)

print("Script completed successfully!")
print(f"Processed {len(combined_faculty_df)} faculty members")
print(f"Found {len(top_items)} top MeSH terms")
print(f"Saved results to faculty_mesh_terms.xlsx and faculty_mesh_terms_matrix.xlsx")